# API

@host = http://localhost:3000/api

### API User

GET {{host}}/user

###

POST {{host}}/user
content-type: application/json

{
  "username": "John"
}

###

GET {{host}}/user/1

###

PATCH {{host}}/user/1
content-type: application/json

{
  "username": "Bob"
}

###

DELETE {{host}}/user/1
